[package]
name = "operating-systems-assessment-1"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["process", "fs"] }

[[bin]]
name = "vssh"
path = "src/bin/vssh.rs"

